// Generated by scripts/build-production.js for gpdata-public-2026-10-01c -- don't edit.
const CACHE_PREFIX = "gpdata-public-";
const CACHE = CACHE_PREFIX + "2026-10-01c";
const PRECACHE = [
  "./",
  "gpbikes-plotter.bundle.min.js?v=2026-10-01c",
  "style.css?v=2026-10-01c",
  "leaflet.css?v=2026-10-01c",
  "pwa.js?v=2026-10-01c",
  "channel-map.json",
  "static/gpbikes-track-map-defaults.json",
  "manifest.webmanifest",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/favicon.svg",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys
      .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE)
      .map((key) => caches.delete(key))))
    .then(() => self.clients.claim()));
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => caches.open(CACHE).then((cache) => cache.match('./'))));
    return;
  }
  event.respondWith(caches.open(CACHE)
    .then((cache) => cache.match(request))
    .then((cached) => cached || fetch(request)));
});
